kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/juanwolf/gomodoro

steps:
- name: test
  image: golang:1.11
  commands:
  - mkdir $GOPATH/bin
  - curl -L -S -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 > $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep
  - dep ensure
  - go test
