builds:
  - binary: gomodoro
    main: gomodoro.go
    ldflags: -s -w
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
  files:
    - README.md
    - LICENSE
release:
  draft: true
