pomodoro_duration = "25m"
break_duration = "5m"
refresh_rate = "1s"
lock_file = "/tmp/gomodoro.pid"

[outputs]

  [outputs.stdout]
  show_percent = false
  size = 80 # Size of the progress bar in characters
  activated = true

  [outputs.file]
  activated = true
  path = "/home/juanwolf/.gomodoro"

  [outputs.slack]
  activated = false
  token = ""
  do_not_disturb = false
  emoji = ":tomato:"